name: Validate-YAML

on:
  push:
    branches: [ main ]
    paths: ['.github/**']
  pull_request:
    branches: [ main ]
    paths: ['.github/**']

  workflow_dispatch:

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: 
            sparse-checkout: .github

    - name: Validate YAML files
      id: lint
      uses: ibiqlik/action-yamllint@v3

    - name: Echo Lint Result
      if: always()
      run: echo ${{ steps.lint.outputs.logfile }}

    - name: Output Logfile
      uses: actions/upload-artifact@v4
      if: always()
      with:
          name: yamllint-logfile
          path: ${{ steps.lint.outputs.logfile }} 